/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/debug`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/add-deck` | `/add-deck`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/deck-gallery` | `/deck-gallery`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/deck-gallery`; params?: Router.UnknownInputParams; } | { pathname: `/[deck]`, params: Router.UnknownInputParams & { deck: string | number; } } | { pathname: `/deck/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/deck/[id]/add-card`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/deck/[id]/results`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/deck/[id]/select-mode`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/deck/[id]/study`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/deck-gallery/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/debug`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/add-deck` | `/add-deck`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/deck-gallery` | `/deck-gallery`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `/deck-gallery`; params?: Router.UnknownOutputParams; } | { pathname: `/[deck]`, params: Router.UnknownOutputParams & { deck: string; } } | { pathname: `/deck/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/deck/[id]/add-card`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/deck/[id]/results`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/deck/[id]/select-mode`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/deck/[id]/study`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/deck-gallery/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/debug${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/add-deck${`?${string}` | `#${string}` | ''}` | `/add-deck${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/deck-gallery${`?${string}` | `#${string}` | ''}` | `/deck-gallery${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/deck-gallery${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/debug`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/add-deck` | `/add-deck`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/deck-gallery` | `/deck-gallery`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/deck-gallery`; params?: Router.UnknownInputParams; } | `/${Router.SingleRoutePart<T>}` | `/deck/${Router.SingleRoutePart<T>}` | `/deck/${Router.SingleRoutePart<T>}/add-card` | `/deck/${Router.SingleRoutePart<T>}/results` | `/deck/${Router.SingleRoutePart<T>}/select-mode` | `/deck/${Router.SingleRoutePart<T>}/study` | `/deck-gallery/${Router.SingleRoutePart<T>}` | { pathname: `/[deck]`, params: Router.UnknownInputParams & { deck: string | number; } } | { pathname: `/deck/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/deck/[id]/add-card`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/deck/[id]/results`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/deck/[id]/select-mode`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/deck/[id]/study`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/deck-gallery/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
